-- MySQL Script generated by MySQL Workbench
-- qua 30 mar 2022 21:36:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema algamoney-api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `algamoney-api` ;

-- -----------------------------------------------------
-- Schema algamoney-api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `algamoney-api` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `algamoney-api` ;

-- -----------------------------------------------------
-- Table `algamoney-api`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`categorias` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8



-- -----------------------------------------------------
-- Table `algamoney-api`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`pessoa` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL COMMENT 'Endereco = Embedable',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `algamoney-api`.`categorias`
-- -----------------------------------------------------
START TRANSACTION;
USE `algamoney-api`;
INSERT INTO `algamoney-api`.`categorias` (`id`, `nome`) VALUES (1, 'Lazer');
INSERT INTO `algamoney-api`.`categorias` (`id`, `nome`) VALUES (2, 'Alimentação');
INSERT INTO `algamoney-api`.`categorias` (`id`, `nome`) VALUES (3, 'Supermercado');
INSERT INTO `algamoney-api`.`categorias` (`id`, `nome`) VALUES (4, 'Farmáçia');
INSERT INTO `algamoney-api`.`categorias` (`id`, `nome`) VALUES (5, 'Outros');

COMMIT;

