-- MySQL Script generated by MySQL Workbench
-- sáb 09 jul 2022 12:25:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema algamoney-api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `algamoney-api` ;

-- -----------------------------------------------------
-- Schema algamoney-api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `algamoney-api` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `algamoney-api` ;

-- -----------------------------------------------------
-- Table `algamoney-api`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`categoria` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `algamoney-api`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`cidade` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `algamoney-api`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nome_UNIQUE` ON `algamoney-api`.`cidade` (`nome` ASC) VISIBLE;

CREATE INDEX `fk_cidade_estado1_idx` ON `algamoney-api`.`cidade` (`estado_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `algamoney-api`.`contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`contato` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`contato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `contato_ibfk_1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `algamoney-api`.`pessoa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_pessoa` ON `algamoney-api`.`contato` (`id_pessoa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `algamoney-api`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`estado` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `algamoney-api`.`lancamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`lancamento` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`lancamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `observacao` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_pessoa` INT NOT NULL,
  `anexo` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `lancamento_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `algamoney-api`.`categoria` (`id`),
  CONSTRAINT `lancamento_ibfk_2`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `algamoney-api`.`pessoa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_categoria` ON `algamoney-api`.`lancamento` (`id_categoria` ASC) VISIBLE;

CREATE INDEX `id_pessoa` ON `algamoney-api`.`lancamento` (`id_pessoa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `algamoney-api`.`permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`permissao` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`permissao` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `algamoney-api`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NULL DEFAULT NULL,
  `logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Endereco = Embedable',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `algamoney-api`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`usuario` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `algamoney-api`.`usuario_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `algamoney-api`.`usuario_permissao` ;

CREATE TABLE IF NOT EXISTS `algamoney-api`.`usuario_permissao` (
  `id_usuario` INT NOT NULL,
  `id_permissao` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_permissao`),
  CONSTRAINT `usuario_permissao_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `algamoney-api`.`usuario` (`id`),
  CONSTRAINT `usuario_permissao_ibfk_2`
    FOREIGN KEY (`id_permissao`)
    REFERENCES `algamoney-api`.`permissao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `id_permissao` ON `algamoney-api`.`usuario_permissao` (`id_permissao` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
